"""
PyInstaller packaging script for Soccer Betting Analysis Tool.

Produces a self-contained folder that non-technical users can run by
double-clicking the executable — no Python, uv, or dependency setup needed.
Chromium browser is bundled inside so Playwright works out of the box.

Usage:
    uv sync --extra build   # install pyinstaller (once)
    uv run python build_package.py

Output:
    dist/足球分析工具/  — zip this folder and distribute to users
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP_NAME = "足球分析工具"
ENTRY_POINT = "launcher.py"


def find_chromium_cache() -> Path | None:
    """Find the local Playwright Chromium cache directory."""
    if sys.platform.startswith("win"):
        base = Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData" / "Local"))
        cache = base / "ms-playwright"
    elif sys.platform == "darwin":
        cache = Path.home() / "Library" / "Caches" / "ms-playwright"
    else:
        cache = Path.home() / ".cache" / "ms-playwright"

    if cache.exists() and any(cache.glob("chromium-*")):
        return cache
    return None


def run_build() -> None:
    """Run PyInstaller and bundle Chromium into the output."""
    browsers_path = find_chromium_cache()
    if not browsers_path:
        print("错误: 未找到 Chromium 缓存。请先运行: uv run playwright install chromium")
        sys.exit(1)

    print(f"打包中...  Chromium 来源: {browsers_path}")

    # PyInstaller uses different separator per platform
    sep = ";" if sys.platform.startswith("win") else ":"
    templates_src = str(HERE / "templates")

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--onedir",
        "--name", APP_NAME,
        "--add-data", f"{templates_src}{sep}templates",
        "--distpath", str(HERE / "dist"),
        "--workpath", str(HERE / "build"),
        "--specpath", str(HERE / "build"),
        "--noconfirm",
        "--clean",
        str(HERE / ENTRY_POINT),
    ]
    subprocess.run(cmd, check=True, cwd=str(HERE))

    # Determine where to place ms-playwright inside the bundle.
    bundle_dir = HERE / "dist" / APP_NAME

    # onedir builds have an _internal directory: copy there for _MEIPASS
    internal = bundle_dir / "_internal"
    if internal.exists():
        dest = internal / "ms-playwright"
    elif sys.platform == "darwin" and (bundle_dir / "Contents" / "MacOS").exists():
        dest = bundle_dir / "Contents" / "Resources" / "ms-playwright"
    else:
        dest = bundle_dir / "ms-playwright"

    if dest.exists():
        shutil.rmtree(dest)
    print(f"复制 Chromium 到: {dest}")
    shutil.copytree(browsers_path, dest)

    # Remove temporary build artifacts
    build_dir = HERE / "build"
    if build_dir.exists():
        shutil.rmtree(build_dir)

    # Remove .spec file generated by PyInstaller
    spec_file = HERE / "build" / f"{APP_NAME}.spec"
    if spec_file.exists():
        spec_file.unlink()

    print(f"\n打包完成!")
    print(f"输出目录: {bundle_dir.resolve()}")
    print(f"将整个 '{APP_NAME}' 文件夹压缩后发给用户，解压后双击即可运行。")


if __name__ == "__main__":
    run_build()
